services:
  kafka: 
    image: apache/kafka:latest  # Usa a imagem oficial do Apache Kafka
    restart: on-failure         # Reinicia somente em caso de falha
    ports: 
      - 9092:9092               # Expõe a porta padrão do Kafka no host
    environment:
      - KAFKA_CFG_BROKER_ID=1                                 # ID único do broker Kafka
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092            # Endereço onde o broker escuta conexões
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092 # Endereço que os clientes vão usar para se conectar
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181            # Endereço do Zookeeper (corrigido)
      - KAFKA_CFG_NUM_PARTITIONS=3                            # Número padrão de partições por tópico
      - ALLOW_PLAINTEXT_LISTENERS=yes                         # Permite conexão sem autenticação (desenvolvimento)
    depends_on:
      - zookeeper  # Garante que o zookeeper esteja ativo antes de iniciar o Kafka

  zookeeper:
    image: bitnami/zookeeper:latest  # Imagem Bitnami do Zookeeper
    ports: 
      - 2181:2181  # Porta padrão do Zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes  # Permite login anônimo para ambiente de desenvolvimento

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest  # Interface visual do Kafka
    ports:
      - 8080:8080  # Porta onde a UI estará disponível (http://localhost:8080)
    environment:
      - KAFKA_CLUSTERS_0_NAME=PlansulBrokerKafka               # Nome de exibição do cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092           # Endereço do broker
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181              # Endereço do Zookeeper
    # volumes:
    #   - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml    # (Opcional) Configuração dinâmica persistente da UI
